### ISSUE TITLE
How do we get this into Coveralls?

### ISSUE THREAD

**Issue by randyzwitch** [JuliaWeb/UAParser.jl#5]
I didn't notice when this package was moved from my personal GitHub to the centralized JuliaWeb, but the README acquired the Coveralls badge. If this is desired, how to we get this repo into Coveralls?

**Comment by IainNZ** [comment]
That was me. It looks like the badges were a little messed up and out-of-date, but I've synched them now.

**Comment by IainNZ** [comment]
Coverage badge is still grey, but it'll refresh soon (coverage is ~80% - can see details by clicking the badge)

**Comment by randyzwitch** [comment]
Thanks, looks like I have a few more tests to write
